# Generated by Django 2.2.5 on 2020-04-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/users/%Y-%m-%d/', verbose_name='profile picture'),
        ),
    ]
