# Generated by Django 2.2.5 on 2020-04-27 11:47

from django.db import migrations, models
import pos.users.models.profiles


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200425_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=pos.users.models.profiles.profile_directory_path, verbose_name='profile picture'),
        ),
    ]
