# Generated by Django 2.2.10 on 2020-05-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_purchases',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
