# Generated by Django 2.2.5 on 2020-04-27 11:47

from django.db import migrations, models
import django.db.models.deletion
import pos.products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='update_at')),
                ('code', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=140)),
                ('image', models.ImageField(blank=True, null=True, upload_to=pos.products.models.image_directory_path, verbose_name='image')),
                ('stock', models.IntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=1, default=0.0, max_digits=19)),
                ('sale_price', models.DecimalField(decimal_places=1, default=0.0, max_digits=19)),
                ('sales', models.IntegerField(default=0)),
                ('fkcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
            ],
            options={
                'ordering': ['-created_at', '-update_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
