# Generated by Django 2.2.5 on 2020-04-30 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='update_at')),
                ('code', models.IntegerField()),
                ('product', models.CharField(max_length=500)),
                ('tax', models.DecimalField(decimal_places=1, default=0.0, max_digits=19)),
                ('net', models.DecimalField(decimal_places=1, default=0.0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=1, default=0.0, max_digits=19)),
                ('payment', models.CharField(max_length=500)),
                ('fkclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('fkuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-update_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
