# Generated by Django 2.2.5 on 2020-05-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='code',
            new_name='invoice',
        ),
    ]
